# Generated by Django 5.1.6 on 2025-02-10 08:47

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('excerpt', models.TextField(help_text='SEO-friendly description', max_length=160)),
                ('featured_image', models.ImageField(upload_to='blog/images/')),
                ('image_alt', models.CharField(help_text='SEO-friendly image description', max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='SEO Meta Title', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Meta Description', max_length=160)),
                ('focus_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=200)),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL if different from current URL')),
                ('robots', models.CharField(default='index,follow', help_text='Robot meta tag values (e.g., index,follow)', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='Blog.tag')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='Blog_post_publish_ddb02a_idx'), models.Index(fields=['slug'], name='Blog_post_slug_30effb_idx'), models.Index(fields=['status'], name='Blog_post_status_bad4b9_idx')],
            },
        ),
    ]
