# Generated by Django 5.1.6 on 2025-02-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_comment_mastercategory_postrevision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(help_text='SEO-friendly description'),
        ),
    ]
