# Generated by Django 5.1.6 on 2025-02-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_category_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='view_count',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
